#!/usr/bin/env node
/**
 * Regenerate the files derived from the rule registry:
 *   rules/README.md              — the index
 *   compliance/COVERAGE.md       — counts
 *   compliance/TRACEABILITY.md   — rule → source → validation matrix
 *
 * Run `npm run build:index` after adding or changing a rule. CI checks the result is current.
 */
import path from "node:path";
import process from "node:process";
import { loadRules, ruleStats } from "../src/lib/rules.mjs";
import { packageRoot, writeFile, read } from "../src/lib/fs.mjs";

const check = process.argv.includes("--check");
const rulesDir = path.join(packageRoot, "rules");
const { rules, errors } = loadRules(rulesDir);

if (errors.length) {
  console.error("cannot build the index while rules are invalid:");
  for (const e of errors) console.error(" -", e);
  process.exit(1);
}

const GROUPS = [
  ["Agent discipline", ["agent", "memory"]],
  ["Engineering", ["architecture", "api", "database", "security", "testing", "devops", "observability", "privacy", "ai"]],
  ["Design", ["accessibility", "components", "content", "data-display", "design-system", "interaction", "localization", "motion", "responsive", "states", "ui", "ux"]],
];

function row(r) {
  const auto = r.validation?.automated ? "yes" : "no";
  return `| [${r.id}](${r.file}) | ${r.title} | ${r.severity} | ${r.priority} | ${r.domain} | ${auto} | ${r.status} |`;
}

function index() {
  const stats = ruleStats(rules);
  const out = [];
  out.push("# Rules registry");
  out.push("");
  out.push("Machine-readable rules with stable IDs. Narrative guidance lives under");
  out.push("[`standard/`](../standard/README.md); these files are what agents and reviews cite.");
  out.push("");
  out.push("Severity is the obligation (`MUST` · `MUST NOT` · `SHOULD` · `MAY`).");
  out.push("Priority is when it blocks (`P0` · `P1` · `P2` · `P3` — see [`MATURITY.md`](../MATURITY.md)).");
  out.push("");
  out.push("> Generated by `npm run build:index`. Edit the rule files, not this page.");
  const seen = new Set();
  for (const [label, domains] of GROUPS) {
    const group = rules.filter((r) => domains.includes(r.domain));
    if (!group.length) continue;
    out.push("");
    out.push(`## ${label}`);
    out.push("");
    out.push("| ID | Title | Severity | Priority | Domain | Auto | Status |");
    out.push("|---|---|---|---|---|---|---|");
    for (const r of group) {
      out.push(row(r));
      seen.add(r.id);
    }
  }
  const rest = rules.filter((r) => !seen.has(r.id));
  if (rest.length) {
    out.push("");
    out.push("## Other");
    out.push("");
    out.push("| ID | Title | Severity | Priority | Domain | Auto | Status |");
    out.push("|---|---|---|---|---|---|---|");
    for (const r of rest) out.push(row(r));
  }
  out.push("");
  out.push(
    `**Total:** ${stats.total} rules · ${stats.active} active · ${stats.automatable} automatable · schema v1`
  );
  out.push("");
  out.push("Lifecycle and supersession: [`LIFECYCLE.md`](LIFECYCLE.md).");
  out.push("");
  return out.join("\n");
}

function coverage() {
  const s = ruleStats(rules);
  const out = [];
  out.push("# Coverage");
  out.push("");
  out.push("> Generated by `npm run build:index`.");
  out.push("");
  out.push("| Metric | Value |");
  out.push("|---|---|");
  out.push(`| Rules total | ${s.total} |`);
  out.push(`| Active | ${s.active} |`);
  for (const sev of ["MUST", "MUST NOT", "SHOULD", "MAY"]) {
    if (s.severity[sev]) out.push(`| ${sev} | ${s.severity[sev]} |`);
  }
  for (const p of ["P0", "P1", "P2", "P3"]) {
    if (s.priority[p]) out.push(`| ${p} | ${s.priority[p]} |`);
  }
  out.push(`| Automatable | ${s.automatable} |`);
  out.push(`| Domains | ${Object.keys(s.domain).length} |`);
  out.push("");
  out.push("## By domain");
  out.push("");
  out.push("| Domain | Rules | P0 |");
  out.push("|---|---|---|");
  for (const d of Object.keys(s.domain).sort()) {
    const p0 = rules.filter((r) => r.domain === d && r.priority === "P0").length;
    out.push(`| ${d} | ${s.domain[d]} | ${p0} |`);
  }
  out.push("");
  out.push(
    "A domain with rules and no automatable check is not a failure — it is a backlog item for [`LEVELS.md`](../LEVELS.md) level 2."
  );
  out.push("");
  return out.join("\n");
}

function traceability() {
  const out = [];
  out.push("# Traceability");
  out.push("");
  out.push("Every rule maps down to something a human or a machine can check.");
  out.push("");
  out.push("```text");
  out.push("Rule ID");
  out.push("   ↓");
  out.push("Authoritative source (REFERENCES.md)");
  out.push("   ↓");
  out.push("Success criterion (when the source has one)");
  out.push("   ↓");
  out.push("Guidance in standard/");
  out.push("   ↓");
  out.push("Checklist item");
  out.push("   ↓");
  out.push("Automated check or recorded manual review");
  out.push("```");
  out.push("");
  out.push("> Generated by `npm run build:index`.");
  out.push("");
  out.push("| Rule | Domain | Severity | Priority | Source | Criteria | Validation |");
  out.push("|---|---|---|---|---|---|---|");
  for (const r of rules) {
    const v = [];
    if (r.validation?.automated) v.push("automated");
    if (r.validation?.manual) v.push("manual");
    const sc = Array.isArray(r.success_criteria) && r.success_criteria.length
      ? r.success_criteria.join(", ")
      : "—";
    out.push(
      `| [${r.id}](../rules/${r.file}) | ${r.domain} | ${r.severity} | ${r.priority} | ${(r.source || []).join(", ")} | ${sc} | ${v.join(" + ") || "—"} |`
    );
  }
  out.push("");
  return out.join("\n");
}

const targets = [
  [path.join(packageRoot, "rules", "README.md"), index()],
  [path.join(packageRoot, "compliance", "COVERAGE.md"), coverage()],
  [path.join(packageRoot, "compliance", "TRACEABILITY.md"), traceability()],
];

let stale = 0;
for (const [file, content] of targets) {
  const rel = path.relative(packageRoot, file).split(path.sep).join("/");
  if (check) {
    const current = (read(file) ?? "").replace(/\r\n/g, "\n");
    if (current !== content) {
      console.error(`stale: ${rel} — run \`npm run build:index\``);
      stale++;
    }
  } else {
    writeFile(file, content);
    console.log(`wrote ${rel}`);
  }
}

if (check && stale) process.exit(1);
if (check) console.log(`generated files are current (${rules.length} rules)`);
